# Docker compose configuration for MySQL database
name: nestjs-langgraph-template
services:
  dev:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_template
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - db-template:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  test:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_template_test
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3307:3306"
    volumes:
      - db-template-test:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
volumes:
  db-template:
  db-template-test:
